AllCops:
  Include:
    - '**/Berksfile'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'

AlignParameters:
  Enabled: false
ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  EnforcedStyle: hash_rockets
LineLength:
  Max: 160
MethodLength:
  Enabled: false
SignalException:
  Enabled: false
TrailingComma:
  Enabled: false
WordArray:
  Enabled: false
